# frozen_string_literal: true
source 'https://supermarket.chef.io'

metadata

cookbook 'chef_hostname', '~> 0.6.1'

cookbook 'sumologic-collector', '~> 1.2.22'

cookbook 'deep-security-agent', '~> 0.3.6'

cookbook 'chef-client'

cookbook 'omnibus-gitlab', git: 'https://gitlab.com/gitlab-org/cookbook-omnibus-gitlab'

cookbook 'jenkins', '~> 5.0.4', :supermarket

cookbook 'java', '~> 1.50.0'

cookbook 'timezone_iii', '~> 1.0.4', :supermarket


