---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] || "You need to export AWS_SSH_KEY_ID in your local dev environment/shell" %>
  vpc_id: <%= ENV['AWS_VPC_ID'] || "You need to export AWS_VPC_ID in your local dev environment/shell" %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] || "You need to export AWS_SUBNET_ID in your local dev environment/shell" %>
  security_group_ids: ["sg-97de9ae6"]
  require_chef_omnibus: true

transport:
  name: ssh
  ssh_key: <%= ENV['SSH_KEY_FILE'] || "You need to export SSH_KEY_FILE in your local dev environment/shell" %>
  connection_timeout: 10
  connection_retries: 5

provisioner:
  name: chef_zero
  attributes:
    sumologic:
      accessid: <%= ENV["SUMO_ACCESS_ID"] || "You need to export SUMO_ACCESS_ID in your local dev environment/shell" %>
      accesskey: <%= ENV["SUMO_ACCESS_KEY"] || "You need to export SUMO_ACCESS_KEY in your local dev environment/shell" %>

platforms:
  # search for our latest AWS Ubuntu AMI
  - name: ubuntu
    driver:
      image_search:
        owner-id: '001085047529'
        name: Ubuntu_*_x64_*

  # search for our latst AWS RHEL AMI
  - name: redhat
    driver:
      image_search:
        owner-id: '001085047529'
        name: RHEL_*_x64_*

  # use our local ubuntu image for offline testing/development
  - name: ubuntu-16.04
    driver:
      name: vagrant

suites:
  - name: local
    excludes:
      - ubuntu
      - ubuntu-16.04
    run_list:
     - recipe[pcs_artifactory::default]
#    attributes:
#      sumologic:
#        accessid:  <%= ENV["SUMO_ACCESS_ID"] || "You need to export SUMO_ACCESS_ID in your local dev environment" %>
#        accesskey: <%= ENV["SUMO_ACCESS_KEY"] || "You need to export SUMO_ACCESS_KEY in your local dev environment" %>
#  - name: integration
#    excludes:
#      - ubuntu-16.04
