---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3
  - name: iamseth/rhel-7.3

verifier: inspec

suites:
  - name: default
    run_list:
      - recipe[pcs_artifactory::default]
    attributes:
      sumologic:
        accessid:  <%= ENV["SUMO_ACCESS_ID"] || "You need to export SUMO_ACCESS_ID in your local dev environment" %>
        accesskey: <%= ENV["SUMO_ACCESS_KEY"] || "You need to export SUMO_ACCESS_ID in your local dev environment" %>
