---
driver:
  name: vagrant
  customize:
    natdnshostresolver1: 'on' #'<%= ENV['USE_MVC_VPN'] == true ? 'on' : 'off'  %>' # this allows us to leverage the OpenVPN connection in our vm
  network:
     - ["private_network", {ip: "192.168.69.69"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[pcs_vault::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      sumologic:
        accessid:  <%= ENV["SUMO_ACCESS_ID"] || "You need to export SUMO_ACCESS_ID in your local dev environment" %>
        accesskey: <%= ENV["SUMO_ACCESS_KEY"] || "You need to export SUMO_ACCESS_ID in your local dev environment" %>
